[package]
name = "droppa"
version = "0.1.0"
edition = "2021"

[dependencies]
rayon = "1.10.0"
anyhow = "1.0.94"
tiny_http = "0.12.0"
multipart = { git = "https://github.com/rakivo/multipart" }

qrcodegen = "1.8.0"
get_if_addrs = "0.5.3"
raylib-light = { version = "0.0.4", features = ["native"] }

[[bin]]
name = "droppa"
path = "main.rs"
